//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmnPardazEpicProject : DbContext
    {
        public AmnPardazEpicProject()
            : base("name=AmnPardazEpicProject")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hrs_Team_Projects> Hrs_Team_Projects { get; set; }
        public virtual DbSet<Hrs_Team_Users> Hrs_Team_Users { get; set; }
        public virtual DbSet<Hrs_Teams> Hrs_Teams { get; set; }
        public virtual DbSet<Prj_Epics> Prj_Epics { get; set; }
        public virtual DbSet<Prj_Projects> Prj_Projects { get; set; }
        public virtual DbSet<Prj_Tasks> Prj_Tasks { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
    }
}
