//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrs_Team_Users
    {
        public decimal Team_UserID { get; set; }
        public decimal TeamID { get; set; }
        public decimal UserID { get; set; }
    
        public virtual Hrs_Teams Hrs_Teams { get; set; }
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
