//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hrs_Team_Projects
    {
        public decimal Team_ProjectID { get; set; }
        public decimal TeamID { get; set; }
        public decimal ProjectID { get; set; }
    
        public virtual Hrs_Teams Hrs_Teams { get; set; }
        public virtual Prj_Projects Prj_Projects { get; set; }
    }
}
