//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Users()
        {
            this.Hrs_Team_Users = new HashSet<Hrs_Team_Users>();
            this.Prj_Tasks = new HashSet<Prj_Tasks>();
        }
    
        public decimal UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public bool LoginEnabled { get; set; }
        public string Password { get; set; }
        public bool Enabled { get; set; }
        public string JobTitle { get; set; }
        public string BusinessImpact { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string TellNo { get; set; }
        public string FaxNo { get; set; }
        public string FaceImage { get; set; }
        public Nullable<System.DateTime> LastChangePasswordDate { get; set; }
        public Nullable<bool> PasswordIsReseted { get; set; }
        public string Label { get; set; }
        public string AuthenticationMethod { get; set; }
        public Nullable<decimal> RegionID { get; set; }
        public Nullable<decimal> SubRegionID { get; set; }
        public Nullable<decimal> SiteID { get; set; }
        public bool C_IsDeleted { get; set; }
        public Nullable<System.DateTime> C_LastModifyDate { get; set; }
        public Nullable<decimal> C_LastModifier { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hrs_Team_Users> Hrs_Team_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prj_Tasks> Prj_Tasks { get; set; }
    }
}
